### PR TITLE
Hello, I translated several environments!

### PR DESCRIPTION
**Pull request by kg1102**
Soon I will translate much more!

### CODE REVIEW

**Comment by kg1102** [comment]
I apologize about a commit I made wrong: "add Chinese introducing" - I corrected the message to: add Portuguese introducing.

**Comment by kg1102** [comment]
fixed lint: [wordpress/pwnscriptum/README.pt-br.md](https://github.com/vulhub/vulhub/pull/329/commits/cd9d19c5ca826326f430557c6bb11fa123b962c9#diff-a8265fe7718e33cb16eeedb9fcc0692f3d12849d418b77ea124947bf253b50e6)

**Comment by Jason9378** [comment]
您的邮件我已接收，我在查阅后会尽快回复，感谢您的来信！

**Comment by LaIMirch** [comment]
Thank you for your message, which has been added to a queuing system. You are currently in 352nd place, and can expect to receive a reply in approximately 19 weeks.

**Pull request closed without merging**
