### PR TITLE
Update README for compose v2

### PR DESCRIPTION
**Pull request by ndeloof**
Docker Compose v2 is now part of the Docker CLI and will install by default with install script as `docker compose`

### CODE REVIEW

**Comment by phith0n** [comment]
thx, I think we should wait at least half a year for people to upgrade the docker~

**Comment by ndeloof** [comment]
kind reminder, It's been 1 year now :)

**Comment by phith0n** [comment]
Thanks for your reminder, I think it's time for migrating to Docker instead of Docker-Compose.

Please refer to the following two suggestions:

1. Because there has been 1 year since your commit, a git rebase is needed
2. Can you add the alternative description (docker-compose) for those who don't have the latest Docker installation

**Comment by ndeloof** [comment]
rebased.

> Can you add the alternative description (docker-compose) for those who don't have the latest Docker installation

Not sure I get your point here. Compose v1 (`docker-compose`) will be "End of Life" next month, and Compose v2 is `docker compose`

**Comment by phith0n** [comment]
@ndeloof 

I know your point. But I think we should at least give some reminders to users of docker-compose that they should upgrade their Docker version to use Docker Compose v2.

**Comment by ndeloof** [comment]
ok, added a note.

**Comment by phith0n** [comment]
Thanks, merge it. And I'll update the Chinese manual later.

**Pull request merged**
